version: '3'

services:
  influx:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      - "INFLUXDB_DB=kismet"
  grafana:
    image: grafana/grafana:7.3.7
    ports:
      - "3000:3000"